apiVersion: apps/v1
kind: Deployment
metadata:
  name: milvus
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: milvus
  template:
    metadata:
      labels:
        app: milvus
    spec:
      containers:
        - name: milvus
          image: "{{ .Values.milvus.image.repository }}:{{ .Values.milvus.image.tag }}"
          ports:
            - containerPort: 19530
            - containerPort: 19121
